In [1]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_csv('../data/processed/stackoverflow_full.csv')

In [3]:
df.head(5)

,Age,Accessibility,EdLevel,Employment,Gender,MentalHealth,MainBranch,YearsCode,YearsCodePro,Country,PreviousSalary,HaveWorkedWith,ComputerSkills,Employed
0,<35,No,Master,1,Man,No,Dev,7,4,Sweden,51552.0,C++;Python;Git;PostgreSQL,4,0
1,<35,No,Undergraduate,1,Man,No,Dev,12,5,Spain,46482.0,Bash/Shell;HTML/CSS;JavaScript;Node.js;SQL;Typ...,12,1
2,<35,No,Master,1,Man,No,Dev,15,6,Germany,77290.0,C;C++;Java;Perl;Ruby;Git;Ruby on Rails,7,0
3,<35,No,Undergraduate,1,Man,No,Dev,9,6,Canada,46135.0,Bash/Shell;HTML/CSS;JavaScript;PHP;Ruby;SQL;Gi...,13,0
4,>35,No,PhD,0,Man,No,NotDev,40,30,Singapore,160932.0,C++;Python,2,0

In [24]:
df_skills = df['HaveWorkedWith']
df_skills.head(5)

0                            C++;Python;Git;PostgreSQL
1    Bash/Shell;HTML/CSS;JavaScript;Node.js;SQL;Typ...
2               C;C++;Java;Perl;Ruby;Git;Ruby on Rails
3    Bash/Shell;HTML/CSS;JavaScript;PHP;Ruby;SQL;Gi...
4                                           C++;Python
Name: HaveWorkedWith, dtype: object

In [25]:
df_skills = df['HaveWorkedWith'].str.split(';',expand=True).stack()
df_skills.tail(10)

73397  7                  Angular
       8                  ASP.NET
       9                   jQuery
       10                React.js
       11                     AWS
       12                DynamoDB
       13    Microsoft SQL Server
       14                  SQLite
73398  0                   Python
       1                   Docker
dtype: object

In [26]:
df_skills = df_skills.reset_index()
df_skills.columns = ['candidate_id','skill_position', 'skill_name']
df_skills = df_skills[['candidate_id','skill_name']]
df_skills.head(10)

   candidate_id  skill_name
0             0         C++
1             0      Python
2             0         Git
3             0  PostgreSQL
4             1  Bash/Shell
5             1    HTML/CSS
6             1  JavaScript
7             1     Node.js
8             1         SQL
9             1  TypeScript

In [28]:
df_skills['skill_name'] = df_skills['skill_name'].str.strip()
df_skills.tail(10)

        candidate_id            skill_name
986454         73397               Angular
986455         73397               ASP.NET
986456         73397                jQuery
986457         73397              React.js
986458         73397                   AWS
986459         73397              DynamoDB
986460         73397  Microsoft SQL Server
986461         73397                SQLite
986462         73398                Python
986463         73398                Docker