In [1]:
import pandas as pd
import numpy as np

In [2]:
df_skills = pd.read_csv('../data/split_tabs/skills_candidate.csv')
df_skills.head(5)

   candidate_id  skill_name
0             0         C++
1             0      Python
2             0         Git
3             0  PostgreSQL
4             1  Bash/Shell

In [3]:
#df_skills_portfolio = df_skills[['skill_name']].drop_duplicates().reset_index(drop=True)
#df_skills_portfolio.index.name = 'skills_id'

In [4]:
# Extraer skills únicas de df_skills
df_skills_catalog = df_skills[['skill_name']].drop_duplicates().reset_index(drop=True)

# Agregar IDs
df_skills_catalog['skills_id'] = range(0, len(df_skills_catalog))

# Reordenar columnas
df_skills_catalog = df_skills_catalog[['skills_id', 'skill_name']]

df_skills_catalog.tail(10)

df_skills_catalog[df_skills_catalog['skill_name'] == 'Python']

   skills_id skill_name
1          1     Python

In [5]:
df_skills_catalog.to_csv('../data/split_tabs/skills.csv',index=False)