In [2]:
import pandas as pd
import numpy as np

In [22]:
df = pd.read_csv('../data/processed/stackoverflow_full.csv')

In [25]:
df.head(5)

,candidate_id,Age,Accessibility,EdLevel,Employment,Gender,MentalHealth,MainBranch,YearsCode,YearsCodePro,Country,PreviousSalary,HaveWorkedWith,ComputerSkills,Employed
work_id,,,,,,,,,,,,,,,
0,0,<35,No,Master,1,Man,No,Dev,7,4,Sweden,51552.0,C++;Python;Git;PostgreSQL,4,0
1,1,<35,No,Undergraduate,1,Man,No,Dev,12,5,Spain,46482.0,Bash/Shell;HTML/CSS;JavaScript;Node.js;SQL;Typ...,12,1
2,2,<35,No,Master,1,Man,No,Dev,15,6,Germany,77290.0,C;C++;Java;Perl;Ruby;Git;Ruby on Rails,7,0
3,3,<35,No,Undergraduate,1,Man,No,Dev,9,6,Canada,46135.0,Bash/Shell;HTML/CSS;JavaScript;PHP;Ruby;SQL;Gi...,13,0
4,4,>35,No,PhD,0,Man,No,NotDev,40,30,Singapore,160932.0,C++;Python,2,0

In [24]:
df.index.name = 'work_id'

In [26]:
df_work = df[['YearsCode','YearsCodePro','ComputerSkills','MainBranch','candidate_id']]
df_work.head(5)

         YearsCode  YearsCodePro  ComputerSkills MainBranch  candidate_id
work_id
0                7             4               4        Dev             0
1               12             5              12        Dev             1
2               15             6               7        Dev             2
3                9             6              13        Dev             3
4               40            30               2     NotDev             4

In [28]:
df_work.to_csv('../data/split_tabs/work.csv')
df_work.head()

         YearsCode  YearsCodePro  ComputerSkills MainBranch  candidate_id
work_id
0                7             4               4        Dev             0
1               12             5              12        Dev             1
2               15             6               7        Dev             2
3                9             6              13        Dev             3
4               40            30               2     NotDev             4