In [2]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\odstf\anaconda3\envs\analyticslessons\lib\site-packages (9.5.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import mysql.connector as sql
import pandas as pd

In [4]:
conexion = sql.connect(host='localhost', port=3307, user='root', password='sql2025.', database='hr_data_project')

In [5]:
cursor = conexion.cursor()

In [6]:
cursor.execute('select * from candidate')
cursor.fetchall()

[(1, '<35', 'Man', 'Sweden'),
 (2, '<35', 'Man', 'Spain'),
 (3, '<35', 'Man', 'Germany'),
 (4, '<35', 'Man', 'Canada'),
 (5, '>35', 'Man', 'Singapore'),
 (6, '<35', 'Man', 'France'),
 (7, '>35', 'Man', 'Germany'),
 (8, '<35', 'Man', 'Switzerland'),
 (9, '>35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (10, '>35', 'Man', 'Russian Federation'),
 (11, '<35', 'Man', 'Israel'),
 (12, '<35', 'Man', 'Turkey'),
 (13, '<35', 'Man', 'Germany'),
 (14, '<35', 'Man', 'United States of America'),
 (15, '<35', 'Man', 'France'),
 (16, '>35', 'Man', 'Brazil'),
 (17, '<35', 'Man', 'Bulgaria'),
 (18, '<35', 'Man', 'Greece'),
 (19, '>35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (20, '>35', 'Man', 'Italy'),
 (21, '<35', 'Man', 'Russian Federation'),
 (22, '>35', 'Man', 'Canada'),
 (23, '>35', 'Man', 'Spain'),
 (24, '>35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (25, '<35', 'Man', 'Netherlands'),
 (26, '>35', 'Man', 'United States of America'),
 (27, '<35', 'Man', 'Poland'),
 (28, '>35', 'Man', 'Canada'),
 (29, '>35', 'Man', 'Sweden'),
 (30, '<35', 'Man', 'Switzerland'),
 (31, '<35', 'Man', 'Hungary'),
 (32, '>35', 'Man', 'Canada'),
 (33, '<35', 'Man', 'United States of America'),
 (34, '>35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (35, '<35', 'Man', 'Netherlands'),
 (36, '<35', 'Man', 'Poland'),
 (37, '<35', 'Man', 'Sweden'),
 (38, '<35', 'Man', 'France'),
 (39, '<35', 'Man', 'Germany'),
 (40, '<35', 'Man', 'Pakistan'),
 (41, '>35', 'Man', 'Switzerland'),
 (42, '<35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (43, '<35', 'Man', 'Spain'),
 (44, '<35', 'Man', 'Nigeria'),
 (45, '<35', 'Man', 'Germany'),
 (46, '<35', 'Man', 'Italy'),
 (47, '<35', 'Man', 'Netherlands'),
 (48, '<35', 'Man', 'Albania'),
 (49, '<35', 'Man', 'United States of America'),
 (50, '<35', 'Man', 'Bangladesh'),
 (51, '>35', 'Man', 'Israel'),
 (52, '<35', 'Man', 'Viet Nam'),
 (53, '<35', 'Man', 'United States of America'),
 (54, '>35', 'Man', 'United States of America'),
 (55, '<35', 'Man', 'Netherlands'),
 (56, '<35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (57, '<35', 'Man', 'Poland'),
 (58, '>35', 'Man', 'Netherlands'),
 (59, '<35', 'Woman', 'Romania'),
 (60, '>35', 'Man', 'United States of America'),
 (61, '<35', 'Man', 'Germany'),
 (62, '<35', 'Woman', 'Russian Federation'),
 (63, '<35', 'Man', 'Sri Lanka'),
 (64, '<35', 'Man', 'France'),
 (65, '>35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (66, '<35', 'Man', 'United States of America'),
 (67, '<35', 'Man', 'India'),
 (68, '>35', 'Man', 'United States of America'),
 (69, '<35', 'Man', 'Switzerland'),
 (70, '<35', 'Man', 'Lithuania'),
 (71, '<35', 'Man', 'Ukraine'),
 (72, '<35', 'Man', 'Israel'),
 (73, '>35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (74, '>35', 'Man', 'Croatia'),
 (75, '<35', 'Man', 'Georgia'),
 (76, '>35', 'Man', 'Canada'),
 (77, '>35', 'Man', 'Italy'),
 (78, '>35', 'Man', 'Denmark'),
 (79, '<35', 'Man', 'Russian Federation'),
 (80, '<35', 'Man', 'Ireland'),
 (81, '>35', 'Man', 'Greece'),
 (82, '>35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (83, '>35', 'Man', 'Poland'),
 (84, '>35', 'Man', 'Romania'),
 (85, '<35', 'Man', 'Lebanon'),
 (86, '>35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (87, '>35', 'Man', 'Bahrain'),
 (88, '<35', 'Man', 'Egypt'),
 (89, '<35', 'Man', 'United States of America'),
 (90, '<35', 'Man', 'Ireland'),
 (91, '<35', 'Man', 'Russian Federation'),
 (92, '<35', 'Man', 'United States of America'),
 (93, '>35', 'Man', 'Colombia'),
 (94, '<35', 'Man', 'Netherlands'),
 (95, '<35', 'Man', 'India'),
 (96, '<35', 'Woman', 'United States of America'),
 (97, '<35', 'Man', 'Greece'),
 (98, '>35', 'Man', 'Australia'),
 (99, '>35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (100, '>35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (101, '>35', 'Man', 'Switzerland'),
 (102, '<35', 'Man', 'Russian Federation'),
 (103, '<35', 'Man', 'Germany'),
 (104, '>35', 'Man', 'Russian Federation'),
 (105, '<35', 'Man', 'Chile'),
 (106, '<35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (107, '<35', 'Man', 'France'),
 (108, '>35', 'Man', 'United States of America'),
 (109, '<35', 'Man', 'Indonesia'),
 (110, '<35', 'Man', 'Germany'),
 (111, '<35', 'Man', 'Iran, Islamic Republic of...'),
 (112, '<35', 'Man', 'Bangladesh'),
 (113, '<35', 'Man', 'France'),
 (114, '<35', 'Man', 'Germany'),
 (115, '<35', 'NonBinary', 'Germany'),
 (116, '<35', 'Man', 'United States of America'),
 (117, '<35', 'Man', 'Netherlands'),
 (118, '>35', 'Man', 'France'),
 (119, '<35', 'Man', 'Portugal'),
 (120, '>35', 'Man', 'Germany'),
 (121, '<35', 'Man', 'Slovakia'),
 (122, '<35', 'Man', 'Bulgaria'),
 (123, '<35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (124, '<35', 'Man', 'India'),
 (125, '<35', 'Man', 'France'),
 (126, '<35', 'Woman', 'Denmark'),
 (127, '<35', 'Man', 'Germany'),
 (128, '<35', 'Man', 'Armenia'),
 (129, '<35', 'Man', 'France'),
 (130, '<35', 'Man', 'Finland'),
 (131, '<35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (132, '>35', 'Man', 'France'),
 (133, '>35', 'Man', 'United States of America'),
 (134, '<35', 'Man', 'Israel'),
 (135, '>35', 'Man', 'United States of America'),
 (136, '<35', 'Man', 'United States of America'),
 (137, '<35', 'Man', 'Hong Kong (S.A.R.)'),
 (138, '>35', 'Man', 'Argentina'),
 (139, '<35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (140, '>35', 'Man', 'United States of America'),
 (141, '<35', 'Man', 'Brazil'),
 (142, '<35', 'Woman', 'Spain'),
 (143, '<35', 'Man', 'Iran, Islamic Republic of...'),
 (144, '<35', 'Man', 'Spain'),
 (145, '>35', 'Man', 'Finland'),
 (146, '<35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (147, '>35', 'Man', 'Costa Rica'),
 (148, '>35', 'Man', 'Netherlands'),
 (149, '<35', 'Man', 'Egypt'),
 (150, '>35', 'Man', 'Germany'),
 (151, '<35', 'Man', 'Egypt'),
 (152, '<35', 'Man', 'United States of America'),
 (153, '<35', 'Woman', 'United States of America'),
 (154, '<35', 'Man', 'Ireland'),
 (155, '>35', 'Man', 'Germany'),
 (156, '>35', 'Man', 'Canada'),
 (157, '>35', 'Man', 'Sweden'),
 (158, '>35', 'Man', 'United States of America'),
 (159, '>35', 'Man', 'Germany'),
 (160, '<35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (161, '<35', 'Man', 'United States of America'),
 (162, '<35', 'Man', 'Romania'),
 (163, '>35', 'Man', 'United States of America'),
 (164, '<35', 'Man', 'Bangladesh'),
 (165, '<35', 'Man', 'Germany'),
 (166, '<35', 'Man', 'Poland'),
 (167, '<35', 'Man', 'Netherlands'),
 (168, '<35', 'Man', 'Canada'),
 (169, '>35', 'Man', 'United States of America'),
 (170, '<35', 'Man', 'Germany'),
 (171, '<35', 'Man', 'Greece'),
 (172, '<35', 'Man', 'India'),
 (173, '<35', 'Woman', 'United States of America'),
 (174, '<35', 'Man', 'Germany'),
 (175, '>35', 'Man', 'France'),
 (176, '<35', 'Man', 'Sweden'),
 (177, '<35', 'Man', 'Canada'),
 (178, '<35', 'Man', 'India'),
 (179, '>35', 'Man', 'Netherlands'),
 (180, '<35', 'Man', 'United States of America'),
 (181, '<35', 'Man', 'Canada'),
 (182, '>35', 'Man', 'Canada'),
 (183, '<35', 'Man', 'Finland'),
 (184, '<35', 'Man', 'Spain'),
 (185, '<35', 'Man', 'Peru'),
 (186, '<35', 'Man', 'Switzerland'),
 (187, '<35', 'NonBinary', 'Germany'),
 (188, '>35', 'Man', 'Russian Federation'),
 (189, '<35', 'Man', 'Greece'),
 (190, '<35', 'Man', 'France'),
 (191, '>35', 'Man', 'Netherlands'),
 (192, '>35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (193, '>35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (194, '<35', 'Man', 'Russian Federation'),
 (195, '>35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (196, '<35', 'Man', 'Greece'),
 (197, '>35', 'Man', 'Japan'),
 (198, '>35', 'Man', 'Poland'),
 (199, '<35', 'Man', 'Belgium'),
 (200, '<35', 'Man', 'United Arab Emirates'),
 (201, '>35', 'Man', 'United States of America'),
 (202, '<35', 'Man', 'United States of America'),
 (203, '<35', 'Man', 'India'),
 (204, '>35', 'Man', 'Switzerland'),
 (205, '<35', 'Man', 'Bolivia'),
 (206, '>35', 'Man', 'United States of America'),
 (207, '<35', 'Man', 'Portugal'),
 (208, '>35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (209, '<35', 'Man', 'Austria'),
 (210, '>35', 'Man', 'France'),
 (211, '<35', 'Man', 'Canada'),
 (212, '<35', 'Man', 'Russian Federation'),
 (213, '<35', 'Man', 'France'),
 (214, '<35', 'Man', 'Sweden'),
 (215, '<35', 'Man', 'Poland'),
 (216, '<35', 'Man', 'Bangladesh'),
 (217, '<35', 'Man', 'United States of America'),
 (218, '<35', 'Man', 'United States of America'),
 (219, '<35', 'Woman', 'Turkey'),
 (220, '<35', 'Man', 'Portugal'),
 (221, '<35', 'Man', 'Ukraine'),
 (222, '<35', 'Man', 'United States of America'),
 (223, '<35', 'Man', 'South Africa'),
 (224, '>35', 'Man', 'France'),
 (225, '<35', 'Man', 'United States of America'),
 (226, '<35', 'Man', 'Netherlands'),
 (227, '<35', 'Man', 'Pakistan'),
 (228, '<35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (229, '<35', 'Man', 'Switzerland'),
 (230, '>35', 'Man', 'United States of America'),
 (231, '<35', 'Man', 'Germany'),
 (232, '>35', 'Man', 'Netherlands'),
 (233, '<35', 'Man', 'Canada'),
 (234, '<35', 'Man', 'United States of America'),
 (235, '<35', 'Man', 'United States of America'),
 (236, '<35', 'Man', 'Spain'),
 (237, '>35', 'Man', 'Switzerland'),
 (238, '<35', 'Man', 'United States of America'),
 (239, '<35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (240, '<35', 'Man', 'Iran, Islamic Republic of...'),
 (241, '<35', 'Man', 'United States of America'),
 (242, '>35', 'Man', 'United States of America'),
 (243, '>35', 'Man', 'Germany'),
 (244, '>35', 'Man', 'Spain'),
 (245, '>35', 'Man', 'Ireland'),
 (246, '<35', 'Man', 'Italy'),
 (247, '<35', 'Man', 'Belgium'),
 (248, '<35', 'Man', 'Germany'),
 (249, '<35', 'Man', 'France'),
 (250, '>35', 'Man', 'Germany'),
 (251, '<35', 'Woman', 'Lebanon'),
 (252, '<35', 'Man', 'Ukraine'),
 (253, '>35', 'Man', 'United States of America'),
 (254, '<35', 'Man', 'Ukraine'),
 (255, '<35', 'Man', 'Turkey'),
 (256, '<35', 'Man', 'Germany'),
 (257, '<35', 'Man', 'Brazil'),
 (258, '<35', 'Man', 'Pakistan'),
 (259, '<35', 'Man', 'France'),
 (260, '<35', 'Man', 'Spain'),
 (261, '>35', 'Man', 'United States of America'),
 (262, '>35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (263, '<35', 'Man', 'United States of America'),
 (264, '<35', 'Man', 'United States of America'),
 (265, '<35', 'Man', 'United States of America'),
 (266, '<35', 'Man', 'India'),
 (267, '>35', 'Man', 'Switzerland'),
 (268, '<35', 'Man', 'United States of America'),
 (269, '>35', 'Man', 'Germany'),
 (270, '<35', 'Man', 'Norway'),
 (271, '<35', 'Man', 'Italy'),
 (272, '>35', 'Man', 'Netherlands'),
 (273, '<35', 'Man', 'France'),
 (274, '<35', 'Man', 'India'),
 (275, '>35', 'Man', 'Austria'),
 (276, '<35', 'Woman', 'Ukraine'),
 (277, '<35', 'NonBinary', 'United States of America'),
 (278, '>35', 'Man', 'Serbia'),
 (279, '>35', 'Man', 'France'),
 (280, '>35', 'Man', 'Italy'),
 (281, '>35', 'Woman', 'United States of America'),
 (282, '<35', 'Man', 'France'),
 (283, '<35', 'Man', 'India'),
 (284, '>35', 'Man', 'United States of America'),
 (285, '<35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (286, '>35', 'Man', 'India'),
 (287, '<35', 'Man', 'Greece'),
 (288, '<35', 'Man', 'India'),
 (289, '<35', 'Man', 'Netherlands'),
 (290, '<35', 'Man', 'Pakistan'),
 (291, '<35', 'Man', 'United States of America'),
 (292, '>35', 'Man', 'Switzerland'),
 (293, '<35', 'Man', 'Italy'),
 (294, '<35', 'Man', 'Sweden'),
 (295, '<35', 'Man', 'Romania'),
 (296, '<35', 'Man', 'India'),
 (297, '<35', 'Man', 'Germany'),
 (298, '<35', 'Man', 'Poland'),
 (299, '<35', 'Man', 'India'),
 (300, '>35', 'Man', 'United States of America'),
 (301, '<35', 'Man', 'Austria'),
 (302, '>35', 'Man', 'Germany'),
 (303, '>35', 'Man', 'Netherlands'),
 (304, '<35', 'Man', 'Poland'),
 (305, '<35', 'Man', 'Bolivia'),
 (306, '>35', 'Man', 'France'),
 (307, '<35', 'Man', 'India'),
 (308, '<35', 'Man', 'Malta'),
 (309, '<35', 'Man', 'Germany'),
 (310, '<35', 'Man', 'United States of America'),
 (311, '<35', 'Man', 'United States of America'),
 (312, '<35', 'Man', 'Finland'),
 (313, '<35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (314, '<35', 'Man', 'Poland'),
 (315, '>35', 'Man', 'Germany'),
 (316, '<35', 'Man', 'United States of America'),
 (317, '<35', 'Man', 'India'),
 (318, '<35', 'Man', 'Netherlands'),
 (319, '<35', 'Man', 'France'),
 (320, '<35', 'Man', 'Poland'),
 (321, '<35', 'Man', 'France'),
 (322, '<35', 'Man', 'France'),
 (323, '<35', 'Man', 'United States of America'),
 (324, '<35', 'Man', 'India'),
 (325, '<35', 'Man', 'United States of America'),
 (326, '<35', 'Woman', 'Iran, Islamic Republic of...'),
 (327, '<35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (328, '<35', 'Man', 'Serbia'),
 (329, '<35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (330, '<35', 'Man', 'Germany'),
 (331, '<35', 'Man', 'Spain'),
 (332, '<35', 'Man', 'Netherlands'),
 (333, '>35', 'Man', 'United States of America'),
 (334, '<35', 'Man', 'Germany'),
 (335, '>35', 'Man', 'Spain'),
 (336, '<35', 'Man', 'Italy'),
 (337, '<35', 'Man', 'Malaysia'),
 (338, '<35', 'Man', 'United States of America'),
 (339, '>35', 'Man', 'Netherlands'),
 (340, '>35', 'Man', 'United States of America'),
 (341, '<35', 'Man', 'Ukraine'),
 (342, '<35', 'Man', 'Iran, Islamic Republic of...'),
 (343, '<35', 'Man', 'Brazil'),
 (344, '>35', 'Man', 'United States of America'),
 (345, '<35', 'Man', 'Belgium'),
 (346, '>35', 'Man', 'Germany'),
 (347, '>35', 'Man', 'United States of America'),
 (348, '<35', 'Man', 'Austria'),
 (349, '>35', 'Man', 'Israel'),
 (350, '>35', 'Woman', 'Canada'),
 (351, '>35', 'Man', 'United States of America'),
 (352, '<35', 'Man', 'Turkey'),
 (353, '>35', 'Man', 'United States of America'),
 (354, '<35', 'Man', 'Turkey'),
 (355, '<35', 'Man', 'Brazil'),
 (356, '<35', 'Man', 'Ukraine'),
 (357, '<35', 'Man', 'France'),
 (358, '<35', 'Man', 'Georgia'),
 (359, '<35', 'Man', 'United States of America'),
 (360, '>35', 'Man', 'United States of America'),
 (361, '<35', 'Man', 'Italy'),
 (362, '<35', 'Man', 'United States of America'),
 (363, '<35', 'Man', 'Czech Republic'),
 (364, '<35', 'Man', 'Poland'),
 (365, '<35', 'Man', 'Germany'),
 (366, '<35', 'NonBinary', 'United States of America'),
 (367, '>35', 'Man', 'United States of America'),
 (368, '<35', 'Man', 'Belarus'),
 (369, '<35', 'Man', 'United States of America'),
 (370, '>35', 'Man', 'Sweden'),
 (371, '<35', 'Man', 'Brazil'),
 (372, '<35', 'Man', 'Sweden'),
 (373, '<35', 'Man', 'Croatia'),
 (374, '<35', 'Man', 'Iran, Islamic Republic of...'),
 (375, '>35', 'Man', 'Germany'),
 (376, '<35', 'Man', 'Australia'),
 (377, '>35', 'Man', 'Sweden'),
 (378, '<35', 'Man', 'India'),
 (379, '>35', 'Man', 'United States of America'),
 (380, '>35', 'Man', 'Israel'),
 (381, '<35', 'Man', 'Canada'),
 (382, '<35', 'Man', 'Poland'),
 (383, '>35', 'Man', 'Switzerland'),
 (384, '<35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (385, '>35', 'Man', 'France'),
 (386, '>35', 'Man', 'France'),
 (387, '<35', 'Man', 'Turkey'),
 (388, '>35', 'Man', 'Belgium'),
 (389, '<35', 'Man', 'United States of America'),
 (390, '<35', 'Man', 'India'),
 (391, '<35', 'Man', 'Germany'),
 (392, '>35', 'Man', 'United States of America'),
 (393, '<35', 'Man', 'United States of America'),
 (394, '>35', 'Woman', 'South Africa'),
 (395, '<35', 'Man', 'India'),
 (396, '<35', 'Man', 'Bangladesh'),
 (397, '<35', 'Man', 'Madagascar'),
 (398, '<35', 'NonBinary', 'Kenya'),
 (399, '<35', 'Man', 'Finland'),
 (400, '<35', 'Man', 'United States of America'),
 (401, '<35', 'Man', 'France'),
 (402, '<35', 'Man', 'Austria'),
 (403, '<35', 'Man', 'India'),
 (404, '<35', 'Man', 'Russian Federation'),
 (405, '>35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (406, '>35', 'Man', 'France'),
 (407, '<35', 'Man', 'Germany'),
 (408, '<35', 'Man', 'Italy'),
 (409, '<35', 'Man', 'Italy'),
 (410, '<35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (411, '<35', 'Man', 'Brazil'),
 (412, '<35', 'Man', 'Iran, Islamic Republic of...'),
 (413, '<35', 'Woman', 'Italy'),
 (414, '>35', 'Man', 'United States of America'),
 (415, '<35', 'Man', 'Brazil'),
 (416, '<35', 'Man', 'Italy'),
 (417, '<35', 'Man', 'Canada'),
 (418, '<35', 'Man', 'United States of America'),
 (419, '<35', 'Man', 'Czech Republic'),
 (420, '<35', 'Man', 'Slovenia'),
 (421, '>35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (422, '<35', 'Man', 'Germany'),
 (423, '<35', 'Man', 'Brazil'),
 (424, '<35', 'Man', 'United States of America'),
 (425, '<35', 'Man', 'Poland'),
 (426, '<35', 'Man', 'Nigeria'),
 (427, '<35', 'Man', 'France'),
 (428, '<35', 'Man', 'Brazil'),
 (429, '<35', 'Man', 'Brazil'),
 (430, '<35', 'Man', 'Belgium'),
 (431, '<35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (432, '<35', 'NonBinary', 'Czech Republic'),
 (433, '<35', 'Man', 'Canada'),
 (434, '<35', 'Man', 'Spain'),
 (435, '<35', 'Man', 'Austria'),
 (436, '<35', 'Man', 'United States of America'),
 (437, '<35', 'Man', 'Malaysia'),
 (438, '<35', 'Man', 'Austria'),
 (439, '<35', 'Man', 'United States of America'),
 (440, '>35', 'Man', 'Brazil'),
 (441, '<35', 'Man', 'United States of America'),
 (442, '<35', 'Man', 'Sweden'),
 (443, '<35', 'Man', 'Germany'),
 (444, '>35', 'Man', 'Netherlands'),
 (445, '<35', 'Man', 'Germany'),
 (446, '<35', 'Man', 'United States of America'),
 (447, '<35', 'Man', 'France'),
 (448, '>35', 'Man', 'Russian Federation'),
 (449, '>35', 'Man', 'Germany'),
 (450, '<35', 'Man', 'Germany'),
 (451, '<35', 'Man', 'Belarus'),
 (452, '<35', 'Man', 'India'),
 (453, '<35', 'Man', 'Singapore'),
 (454, '>35', 'Man', 'Italy'),
 (455, '<35', 'Man', 'United States of America'),
 (456, '<35', 'Man', 'Canada'),
 (457, '<35', 'Man', 'Hungary'),
 (458, '>35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (459, '>35', 'Man', 'Greece'),
 (460, '>35', 'Man', 'United States of America'),
 (461, '>35', 'Man', 'United States of America'),
 (462, '<35', 'Man', 'United States of America'),
 (463, '<35', 'Man', 'United Kingdom of Great Britain and Northern Ireland'),
 (464, '>35', 'NonBinary', 'Belgium'),
 (465, '<35', 'Man', 'Germany'),
 (466, '<35', 'Man', 'Poland'),
 (467, '<35', 'Man', 'Germany'),
 (468, '<35', 'Man', 'Pakistan'),
 (469, '>35', 'Man', 'Czech Republic'),
 (470, '<35', 'Man', 'India'),
 (471, '<35', 'Man', 'Germany'),
 (472, '>35', 'Man', 'United States of America'),
 (473, '<35', 'Man', 'Austria'),
 (474, '<35', 'Man', 'India'),
 (475, '<35', 'Man', 'Germany'),
 (476, '<35', 'Man', 'Germany'),
 (477, '>35', 'Man', 'Germany'),
 (478, '<35', 'Man', 'Kenya'),
 (479, '>35', 'Man', 'United States of America'),
 (480, '>35', 'Man', 'United States of America'),
 (481, '<35', 'Man', 'Turkey'),
 (482, '<35', 'Man', 'Czech Republic'),
 (483, '<35', 'Man', 'India'),
 (484, '>35', 'Man', 'Netherlands'),
 (485, '<35', 'Man', 'Netherlands'),
 (486, '<35', 'Man', 'Brazil'),
 (487, '<35', 'Man', 'India'),
 (488, '<35', 'Man', 'Russian Federation'),
 (489, '<35', 'Man', 'India'),
 (490, '>35', 'Man', 'United States of America'),
 (491, '<35', 'Man', 'India'),
 (492, '>35', 'Man', 'Israel'),
 (493, '<35', 'Man', 'Czech Republic'),
 (494, '<35', 'Man', 'United States of America'),
 (495, '<35', 'Man', 'Colombia'),
 (496, '<35', 'Man', 'France'),
 (497, '<35', 'Man', 'Netherlands'),
 (498, '>35', 'Man', 'United States of America'),
 (499, '<35', 'Man', 'India'),
 (500, '<35', 'Man', 'Russian Federation'),
 (501, '<35', 'Man', 'Bangladesh'),

In [7]:
cursor.close()

True

In [27]:
# Rutas de los archivos CSV
paths = {
    # 'main_data': '../data/processed/victimas_por_hechos_departamental_20250416.csv'
    'candidate': '../data/split_tabs/candidate.csv',
    'educational_information': '../data/split_tabs/educational_information.csv',
    'recruitment_information': '../data/split_tabs/recruitment_information.csv',
    'skills': '../data/split_tabs/skills.csv',
    'work_skills': '../data/split_tabs/work_skills.csv',
    'work': '../data/split_tabs/work.csv',
      # reporte_hecho y grupo_poblacional misma PK
}

# Diccionario para guardar los DataFrames cargados
dfs = {}

for name, path in paths.items():
    try:
        # Intentar cargar con UTF-8
        df = pd.read_csv(path, encoding='utf-8')
    except UnicodeDecodeError:
        try:
            # Intentar cargar con Latin1 si falla UTF-8
            df = pd.read_csv(path, encoding='latin1')
        except Exception as e:
            print(f"❌ Error cargando '{name}' desde '{path}': {e}")
            df = None
    dfs[name] = df

# Mostrar resumen de la carga
print("\n📦 Resumen de archivos cargados:")
for name, df in dfs.items():
    if df is not None:
        print(f"✅ '{name}' cargado con éxito. Filas: {df.shape[0]}, Columnas: {df.shape[1]}")
    else:
        print(f"⚠️ '{name}' no se cargó correctamente.")

📦 Resumen de archivos cargados:
✅ 'candidate' cargado con éxito. Filas: 73462, Columnas: 4
✅ 'educational_information' cargado con éxito. Filas: 73462, Columnas: 3
✅ 'recruitment_information' cargado con éxito. Filas: 73462, Columnas: 5
✅ 'skills' cargado con éxito. Filas: 116, Columnas: 2
✅ 'work_skills' cargado con éxito. Filas: 986464, Columnas: 3
✅ 'work' cargado con éxito. Filas: 73462, Columnas: 6

In [9]:
dfs['candidate']

,candidate_id,Age,Gender,Country
0,0,<35,Man,Sweden
1,1,<35,Man,Spain
2,2,<35,Man,Germany
3,3,<35,Man,Canada
4,4,>35,Man,Singapore
...,...,...,...,...
73457,73457,<35,Man,Germany
73458,73458,>35,Man,United States of America
73459,73459,<35,Man,Nigeria
73460,73460,<35,Man,United States of America
73461,73461,<35,NonBinary,United Kingdom of Great Britain and Northern I...

In [10]:
conexion = sql.connect(host='localhost', port=3307, user='root', password='sql2025.', database='hr_data_project')
cursor = conexion.cursor()

df_candidate = dfs['candidate']

# Iterar sobre las filas del DataFrame
for _, row in df_candidate.iterrows():
    try:
        query = """
            INSERT INTO candidate(candidate_id, age, gender, country)
            VALUES (%s, %s,%s, %s)
        """
        values = (int (row['candidate_id'])+1, row['Age'], row['Gender'], row['Country'])  # Asegurar el tipo entero
        cursor.execute(query, values)
    except Exception as e:
        print(f"❌ Error insertando el candidate con ID {row['candidate_id']}: {e}")

# Confirmar los cambios
conexion.commit()
print("✅ Inserción completada en candidate.")

cursor.close()
conexion.close()

❌ Error insertando el candidate con ID 0: 1062 (23000): Duplicate entry '1' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 1: 1062 (23000): Duplicate entry '2' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 2: 1062 (23000): Duplicate entry '3' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 3: 1062 (23000): Duplicate entry '4' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 4: 1062 (23000): Duplicate entry '5' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 5: 1062 (23000): Duplicate entry '6' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 6: 1062 (23000): Duplicate entry '7' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 7: 1062 (23000): Duplicate entry '8' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 8: 1062 (23000): Duplicate entry '9' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 9: 1062 (23000): Duplicate entry '10' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 10: 1062 (23000): Duplicate entry '11' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 11: 1062 (23000): Duplicate entry '12' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 12: 1062 (23000): Duplicate entry '13' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 13: 1062 (23000): Duplicate entry '14' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 14: 1062 (23000): Duplicate entry '15' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 15: 1062 (23000): Duplicate entry '16' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 16: 1062 (23000): Duplicate entry '17' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 17: 1062 (23000): Duplicate entry '18' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 18: 1062 (23000): Duplicate entry '19' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 19: 1062 (23000): Duplicate entry '20' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 20: 1062 (23000): Duplicate entry '21' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 21: 1062 (23000): Duplicate entry '22' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 22: 1062 (23000): Duplicate entry '23' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 23: 1062 (23000): Duplicate entry '24' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 24: 1062 (23000): Duplicate entry '25' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 25: 1062 (23000): Duplicate entry '26' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 26: 1062 (23000): Duplicate entry '27' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 27: 1062 (23000): Duplicate entry '28' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 28: 1062 (23000): Duplicate entry '29' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 29: 1062 (23000): Duplicate entry '30' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 30: 1062 (23000): Duplicate entry '31' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 31: 1062 (23000): Duplicate entry '32' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 32: 1062 (23000): Duplicate entry '33' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 33: 1062 (23000): Duplicate entry '34' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 34: 1062 (23000): Duplicate entry '35' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 35: 1062 (23000): Duplicate entry '36' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 36: 1062 (23000): Duplicate entry '37' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 37: 1062 (23000): Duplicate entry '38' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 38: 1062 (23000): Duplicate entry '39' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 39: 1062 (23000): Duplicate entry '40' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 40: 1062 (23000): Duplicate entry '41' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 41: 1062 (23000): Duplicate entry '42' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 42: 1062 (23000): Duplicate entry '43' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 43: 1062 (23000): Duplicate entry '44' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 44: 1062 (23000): Duplicate entry '45' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 45: 1062 (23000): Duplicate entry '46' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 46: 1062 (23000): Duplicate entry '47' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 47: 1062 (23000): Duplicate entry '48' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 48: 1062 (23000): Duplicate entry '49' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 49: 1062 (23000): Duplicate entry '50' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 50: 1062 (23000): Duplicate entry '51' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 51: 1062 (23000): Duplicate entry '52' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 52: 1062 (23000): Duplicate entry '53' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 53: 1062 (23000): Duplicate entry '54' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 54: 1062 (23000): Duplicate entry '55' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 55: 1062 (23000): Duplicate entry '56' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 56: 1062 (23000): Duplicate entry '57' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 57: 1062 (23000): Duplicate entry '58' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 58: 1062 (23000): Duplicate entry '59' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 59: 1062 (23000): Duplicate entry '60' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 60: 1062 (23000): Duplicate entry '61' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 61: 1062 (23000): Duplicate entry '62' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 62: 1062 (23000): Duplicate entry '63' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 63: 1062 (23000): Duplicate entry '64' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 64: 1062 (23000): Duplicate entry '65' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 65: 1062 (23000): Duplicate entry '66' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 66: 1062 (23000): Duplicate entry '67' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 67: 1062 (23000): Duplicate entry '68' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 68: 1062 (23000): Duplicate entry '69' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 69: 1062 (23000): Duplicate entry '70' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 70: 1062 (23000): Duplicate entry '71' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 71: 1062 (23000): Duplicate entry '72' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 72: 1062 (23000): Duplicate entry '73' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 73: 1062 (23000): Duplicate entry '74' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 74: 1062 (23000): Duplicate entry '75' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 75: 1062 (23000): Duplicate entry '76' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 76: 1062 (23000): Duplicate entry '77' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 77: 1062 (23000): Duplicate entry '78' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 78: 1062 (23000): Duplicate entry '79' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 79: 1062 (23000): Duplicate entry '80' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 80: 1062 (23000): Duplicate entry '81' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 81: 1062 (23000): Duplicate entry '82' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 82: 1062 (23000): Duplicate entry '83' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 83: 1062 (23000): Duplicate entry '84' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 84: 1062 (23000): Duplicate entry '85' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 85: 1062 (23000): Duplicate entry '86' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 86: 1062 (23000): Duplicate entry '87' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 87: 1062 (23000): Duplicate entry '88' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 88: 1062 (23000): Duplicate entry '89' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 89: 1062 (23000): Duplicate entry '90' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 90: 1062 (23000): Duplicate entry '91' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 91: 1062 (23000): Duplicate entry '92' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 92: 1062 (23000): Duplicate entry '93' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 93: 1062 (23000): Duplicate entry '94' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 94: 1062 (23000): Duplicate entry '95' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 95: 1062 (23000): Duplicate entry '96' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 96: 1062 (23000): Duplicate entry '97' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 97: 1062 (23000): Duplicate entry '98' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 98: 1062 (23000): Duplicate entry '99' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 99: 1062 (23000): Duplicate entry '100' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 100: 1062 (23000): Duplicate entry '101' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 101: 1062 (23000): Duplicate entry '102' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 102: 1062 (23000): Duplicate entry '103' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 103: 1062 (23000): Duplicate entry '104' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 104: 1062 (23000): Duplicate entry '105' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 105: 1062 (23000): Duplicate entry '106' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 106: 1062 (23000): Duplicate entry '107' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 107: 1062 (23000): Duplicate entry '108' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 108: 1062 (23000): Duplicate entry '109' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 109: 1062 (23000): Duplicate entry '110' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 110: 1062 (23000): Duplicate entry '111' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 111: 1062 (23000): Duplicate entry '112' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 112: 1062 (23000): Duplicate entry '113' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 113: 1062 (23000): Duplicate entry '114' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 114: 1062 (23000): Duplicate entry '115' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 115: 1062 (23000): Duplicate entry '116' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 116: 1062 (23000): Duplicate entry '117' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 117: 1062 (23000): Duplicate entry '118' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 118: 1062 (23000): Duplicate entry '119' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 119: 1062 (23000): Duplicate entry '120' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 120: 1062 (23000): Duplicate entry '121' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 121: 1062 (23000): Duplicate entry '122' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 122: 1062 (23000): Duplicate entry '123' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 123: 1062 (23000): Duplicate entry '124' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 124: 1062 (23000): Duplicate entry '125' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 125: 1062 (23000): Duplicate entry '126' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 126: 1062 (23000): Duplicate entry '127' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 127: 1062 (23000): Duplicate entry '128' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 128: 1062 (23000): Duplicate entry '129' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 129: 1062 (23000): Duplicate entry '130' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 130: 1062 (23000): Duplicate entry '131' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 131: 1062 (23000): Duplicate entry '132' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 132: 1062 (23000): Duplicate entry '133' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 133: 1062 (23000): Duplicate entry '134' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 134: 1062 (23000): Duplicate entry '135' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 135: 1062 (23000): Duplicate entry '136' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 136: 1062 (23000): Duplicate entry '137' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 137: 1062 (23000): Duplicate entry '138' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 138: 1062 (23000): Duplicate entry '139' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 139: 1062 (23000): Duplicate entry '140' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 140: 1062 (23000): Duplicate entry '141' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 141: 1062 (23000): Duplicate entry '142' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 142: 1062 (23000): Duplicate entry '143' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 143: 1062 (23000): Duplicate entry '144' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 144: 1062 (23000): Duplicate entry '145' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 145: 1062 (23000): Duplicate entry '146' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 146: 1062 (23000): Duplicate entry '147' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 147: 1062 (23000): Duplicate entry '148' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 148: 1062 (23000): Duplicate entry '149' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 149: 1062 (23000): Duplicate entry '150' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 150: 1062 (23000): Duplicate entry '151' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 151: 1062 (23000): Duplicate entry '152' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 152: 1062 (23000): Duplicate entry '153' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 153: 1062 (23000): Duplicate entry '154' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 154: 1062 (23000): Duplicate entry '155' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 155: 1062 (23000): Duplicate entry '156' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 156: 1062 (23000): Duplicate entry '157' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 157: 1062 (23000): Duplicate entry '158' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 158: 1062 (23000): Duplicate entry '159' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 159: 1062 (23000): Duplicate entry '160' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 160: 1062 (23000): Duplicate entry '161' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 161: 1062 (23000): Duplicate entry '162' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 162: 1062 (23000): Duplicate entry '163' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 163: 1062 (23000): Duplicate entry '164' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 164: 1062 (23000): Duplicate entry '165' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 165: 1062 (23000): Duplicate entry '166' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 166: 1062 (23000): Duplicate entry '167' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 167: 1062 (23000): Duplicate entry '168' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 168: 1062 (23000): Duplicate entry '169' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 169: 1062 (23000): Duplicate entry '170' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 170: 1062 (23000): Duplicate entry '171' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 171: 1062 (23000): Duplicate entry '172' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 172: 1062 (23000): Duplicate entry '173' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 173: 1062 (23000): Duplicate entry '174' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 174: 1062 (23000): Duplicate entry '175' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 175: 1062 (23000): Duplicate entry '176' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 176: 1062 (23000): Duplicate entry '177' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 177: 1062 (23000): Duplicate entry '178' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 178: 1062 (23000): Duplicate entry '179' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 179: 1062 (23000): Duplicate entry '180' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 180: 1062 (23000): Duplicate entry '181' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 181: 1062 (23000): Duplicate entry '182' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 182: 1062 (23000): Duplicate entry '183' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 183: 1062 (23000): Duplicate entry '184' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 184: 1062 (23000): Duplicate entry '185' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 185: 1062 (23000): Duplicate entry '186' for key 'candidate.PRIMARY'
❌ Error insertando el candidate con ID 186: 1062 (23000): Duplicate entry '187' for key 'candidate.PRIMARY'

KeyboardInterrupt:

In [ ]:
dfs['recruitment_information']

       recruitment_id  PreviousSalary  Employed MentalHealth  candidate_id
0                   0         51552.0         0           No             0
1                   1         46482.0         1           No             1
2                   2         77290.0         0           No             2
3                   3         46135.0         0           No             3
4                   4        160932.0         0           No             4
...               ...             ...       ...          ...           ...
73457           73457         41058.0         1           No         73457
73458           73458        115000.0         1           No         73458
73459           73459         57720.0         1           No         73459
73460           73460         70000.0         1          Yes         73460
73461           73461         75384.0         0           No         73461

[73462 rows x 5 columns]

In [ ]:
dfs['candidate']

,candidate_id,Age,Gender,Country
0,0,<35,Man,Sweden
1,1,<35,Man,Spain
2,2,<35,Man,Germany
3,3,<35,Man,Canada
4,4,>35,Man,Singapore
...,...,...,...,...
73457,73457,<35,Man,Germany
73458,73458,>35,Man,United States of America
73459,73459,<35,Man,Nigeria
73460,73460,<35,Man,United States of America
73461,73461,<35,NonBinary,United Kingdom of Great Britain and Northern I...

In [11]:
conexion = sql.connect(host='localhost', port=3307, user='root', password='sql2025.', database='hr_data_project')
cursor = conexion.cursor()

df_recruitment_information = dfs['recruitment_information']

# Iterar sobre las filas del DataFrame
for _, row in df_recruitment_information.iterrows():
    try:
        query = """
            INSERT INTO recruitment_information(recruitment_id, previous_salary, employed, mental_health, candidate_id)
            VALUES (%s, %s,%s, %s, %s)
        """
        values = (int (row['recruitment_id'])+1, row['PreviousSalary'], row['Employed'], row['MentalHealth'], int (row['candidate_id'])+1)  # Asegurar el tipo entero
        cursor.execute(query, values)
    except Exception as e:
        print(f"❌ Error insertando el recruitment_information con ID {row['recruitment_id']}: {e}")

# Confirmar los cambios
conexion.commit()
print("✅ Inserción completada en recruitment_information.")

cursor.close()
conexion.close()

✅ Inserción completada en recruitment_information.

In [12]:
dfs['educational_information']

       education_id        EdLevel  candidate_id
0                 0         Master             0
1                 1  Undergraduate             1
2                 2         Master             2
3                 3  Undergraduate             3
4                 4            PhD             4
...             ...            ...           ...
73457         73457  Undergraduate         73457
73458         73458  Undergraduate         73458
73459         73459  Undergraduate         73459
73460         73460  Undergraduate         73460
73461         73461         Master         73461

[73462 rows x 3 columns]

In [15]:
conexion = sql.connect(host='localhost', port=3307, user='root', password='sql2025.', database='hr_data_project')
cursor = conexion.cursor()

df_educational_information = dfs['educational_information']

# Iterar sobre las filas del DataFrame
for _, row in df_educational_information.iterrows():
    try:
        query = """
            INSERT INTO educational_information(education_id, edlevel, candidate_id)
            VALUES (%s, %s, %s)
        """
        values = (int (row['education_id'])+1, row['EdLevel'], int (row['candidate_id'])+1)  # Asegurar el tipo entero
        cursor.execute(query, values)
    except Exception as e:
        print(f"❌ Error insertando el educational_information con ID {row['education_id']}: {e}")

# Confirmar los cambios
conexion.commit()
print("✅ Inserción completada en educational_information.")

cursor.close()
conexion.close()

✅ Inserción completada en educational_information.

In [16]:
dfs['work']

,work_id,YearsCode,YearsCodePro,ComputerSkills,MainBranch,candidate_id
0,0,7,4,4,Dev,0
1,1,12,5,12,Dev,1
2,2,15,6,7,Dev,2
3,3,9,6,13,Dev,3
4,4,40,30,2,NotDev,4
...,...,...,...,...,...,...
73457,73457,7,2,13,Dev,73457
73458,73458,21,16,11,Dev,73458
73459,73459,4,3,12,Dev,73459
73460,73460,5,1,15,Dev,73460
73461,73461,10,3,2,Dev,73461

In [17]:
conexion = sql.connect(host='localhost', port=3307, user='root', password='sql2025.', database='hr_data_project')
cursor = conexion.cursor()

df_work = dfs['work']

# Iterar sobre las filas del DataFrame
for _, row in df_work.iterrows():
    try:
        query = """
            INSERT INTO work(work_id, years_code, years_code_pro, computer_skills, main_branch, candidate_id)
            VALUES (%s, %s, %s,%s, %s, %s)
        """
        values = (int (row['work_id'])+1, row['YearsCode'], row['YearsCodePro'],row['ComputerSkills'],row['MainBranch'], int (row['candidate_id'])+1)  # Asegurar el tipo entero
        cursor.execute(query, values)
    except Exception as e:
        print(f"❌ Error insertando el work con ID {row['work_id']}: {e}")

# Confirmar los cambios
conexion.commit()
print("✅ Inserción completada en work.")

cursor.close()
conexion.close()

✅ Inserción completada en work.

In [19]:
dfs['skills']

     skills_id      skill_name
0            0             C++
1            1          Python
2            2             Git
3            3      PostgreSQL
4            4      Bash/Shell
..         ...             ...
111        111  Play Framework
112        112         Phoenix
113        113           OCaml
114        114      Colocation
115        115        Solidity

[116 rows x 2 columns]

In [22]:
conexion = sql.connect(host='localhost', port=3307, user='root', password='sql2025.', database='hr_data_project')
cursor = conexion.cursor()

df_skills = dfs['skills']

# Iterar sobre las filas del DataFrame
for _, row in df_skills.iterrows():
    try:
        query = """
            INSERT INTO skills (skills_id, skill_name)
            VALUES (%s, %s)
        """
        values = (int (row['skills_id'])+1, row['skill_name'])  # Asegurar el tipo entero
        cursor.execute(query, values)
    except Exception as e:
        print(f"❌ Error insertando el skill con ID {row['skills_id']}: {e}")

# Confirmar los cambios
conexion.commit()
print("✅ Inserción completada en skill.")

cursor.close()
conexion.close()

✅ Inserción completada en skill.

In [28]:
dfs['work_skills']

        work_skills_id  work_id  skills_id
0                    0        0          0
1                    1        0          1
2                    2        0          2
3                    3        0          3
4                    4        1          4
...                ...      ...        ...
986459          986459    73397         29
986460          986460    73397         44
986461          986461    73397         52
986462          986462    73398          1
986463          986463    73398         23

[986464 rows x 3 columns]

In [30]:
conexion = sql.connect(host='localhost', port=3307, user='root', password='sql2025.', database='hr_data_project')
cursor = conexion.cursor()

df_work_skills = dfs['work_skills']

# Iterar sobre las filas del DataFrame
for _, row in df_work_skills.iterrows():
    try:
        query = """
            INSERT INTO work_skills(work_skills_id, work_id, skills_id)
            VALUES (%s, %s, %s)
        """
        values = (int (row['work_skills_id'])+1, int (row['work_id'])+1, int (row['skills_id'])+1)  # Asegurar el tipo entero
        cursor.execute(query, values)
    except Exception as e:
        print(f"❌ Error insertando el work_skills con ID {row['work_skills_id']}: {e}")

# Confirmar los cambios
conexion.commit()
print("✅ Inserción completada en work_skills.")

cursor.close()
conexion.close()

✅ Inserción completada en work_skills.